# Generated by Django 4.2.28 on 2026-02-11 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_path', models.CharField(max_length=512)),
                ('upscaled_path', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('uploaded', '업로드됨'), ('queued', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='queued', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=512, null=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'photos_photorecord',
                'ordering': ['-created_at'],
            },
        ),
    ]
